In [3]:
import pandas as pd
import numpy as np

In [4]:
s = pd.Series([1,2,3,4,5,6])
print(s)

age = pd.Series([25,26,39,23], index= ["gagan", "vasu", "mayank", "shivi"])
print(age)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
gagan     25
vasu      26
mayank    39
shivi     23
dtype: int64

In [5]:
info = {
        "name" : ["gagan", "vasu" , "shivi"],
        "age"  : [23, 35 ,26],
        "group" : ["A+", "O+", "AB+"]
}

data = pd.DataFrame(info)
print(data)
print(type(data))
print(data.columns)
print(data.index)

np_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
df = pd.DataFrame(np_array, columns=["col1", "col2","col3"])
print(df)

    name  age group
0  gagan   23    A+
1   vasu   35    O+
2  shivi   26   AB+
<class 'pandas.core.frame.DataFrame'>
Index(['name', 'age', 'group'], dtype='object')
RangeIndex(start=0, stop=3, step=1)
   col1  col2  col3
0     1     2     3
1     4     5     6
2     7     8     9

In [6]:
data = pd.read_csv("employee_data.csv")
print(data, type(data))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [7]:
df = pd.read_csv("employee_data.csv")

print(df.head(2))
print(df.tail(2))
print(df.count())
print(df.sample())
print(df.columns)
print(df.shape)
print(df.nunique())
print(df.describe())

   ID   Name  Age Department  Salary
0   1  Alice   25         HR   55000
1   2    Bob   32         IT   72000
   ID   Name  Age Department  Salary
8   9    Ian   35         IT   75000
9  10  Julia   30    Finance   60000
ID            10
Name          10
Age           10
Department    10
Salary        10
dtype: int64
   ID   Name  Age Department  Salary
3   4  David   45  Marketing   91000
Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='object')
(10, 5)
ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64
             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [8]:
df = pd.read_csv("globalAirQuality.csv")
df
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [9]:
df["country"]
df[["city", "aqi"]]

df.loc[0]
df.loc[0:3]
df.iloc[0:3]

df.loc[0, "country"]
df.iloc[0, 2]

df.iloc[0:3, 1:5]
df.loc[0:3, ["country", "aqi"]]

  country  aqi
0      US  108
1      US   90
2      US   84
3      US  158

In [10]:
df[df["aqi"] > 100]
df[df["aqi"] > 100][["city", "aqi"]]

df[(df["aqi"] > 100) & (df["timestamp"] == "2025-11-04 18:25:17.554219")]

aqi_data = df[(df["aqi"] > 100) & (df["timestamp"] == "2025-11-04 18:25:17.554219")][["city", "aqi"]]
aqi_data.loc[360]
aqi_data.iloc[1]

df.query("aqi > 100 & timestamp == '2025-11-04 18:25:17.554219'")

my_country = "IN"
df.query("country == @my_country")

df["timestamp"] = pd.to_datetime(df["timestamp"])
df["date"] = df["timestamp"].dt.date
selected_date = pd.to_datetime("2025-11-04").date()

df.query("country == @my_country & date == @selected_date & aqi > 100")

# Use .copy() to avoid confusion
countries = df[["country", "aqi"]].copy()
countries.loc[0:4, "country"] = "India"

print(countries)

      country  aqi
0       India  108
1       India   90
2       India   84
3       India  158
4       India   97
...       ...  ...
17995      CH  103
17996      CH  105
17997      CH  122
17998      CH   95
17999      CH   88

[18000 rows x 2 columns]

In [11]:
df = pd.read_csv("raw_data.csv")

df.isnull()
df.isnull().sum()

df.dropna()
df.dropna(axis=1)

df.fillna(0)
df["age"] = df["age"].fillna(df["age"].mean())
df["age"]

df.ffill()
df.bfill()

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female  51000.0
5    5        Li Wei  27.00   China     Male  51000.0
6    6    Ahmed Khan  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     USA     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [12]:
df = pd.read_csv("raw_data.csv")

df.duplicated()
df.duplicated("country")
df.duplicated(["country", "gender"])

df.drop_duplicates()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [13]:
df= pd.read_csv("raw_data.csv")
df.dtypes
df2 = df.fillna(0).copy()
df2["income"] = df2["income"].astype(int)
df2["age"] = df2["age"].astype(int)
df2["name"].str.split(" ")
type(df2["name"].str.split(" ")[0])            
df2["country"].str.contains("US")
df2["country"].str.contains("india", case=False)

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object

In [14]:
df2 = df.copy()

df2["Tax"] = df2["income"].apply(lambda x: "10%" if x< 60000 else "20%")

new_gender = {"Male" : "M", "Female": "F", "Unknown": "U"}
df2["gender"] = df2["gender"].map(new_gender)

df2 = df2.assign(new_income = df2["income"] * 1.1)

df2["country"].replace("USA", "United States Of America")
df2

    id          name   age country gender   income  Tax  new_income
0    1      John Doe  29.0     USA      M  55000.0  10%     60500.0
1    1      John Doe  29.0     USA      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN     USA      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  20%         NaN
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0     USA      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0     USA    NaN  58000.0  10%     63800.0

In [15]:
df2 = df.copy()

df2 = df2.rename(columns= {"income": "Salary"})
df2= df2.rename(index={0: "first"})

df2.sort_values("Salary")
df2.sort_values("Salary", ascending= False)

df2.sort_values(["age","Salary"])

df2["ranking"] = df2["Salary"].rank(ascending= False, method="dense")
df2

       id          name   age country   gender   Salary  ranking
first   1      John Doe  29.0     USA     Male  55000.0      5.0
1       1      John Doe  29.0     USA     Male  55000.0      5.0
2       2    Jane Smith   NaN  Canada   Female  62000.0      3.0
3       3          Alex   NaN     USA  Unknown  47000.0      7.0
4       4  Maria Garcia  34.0   Spain   Female      NaN      NaN
5       5        Li Wei  27.0   China     Male  51000.0      6.0
6       6           NaN  45.0   India   Female  73000.0      1.0
7       7    Ahmed Khan  38.0     NaN     Male  68000.0      2.0
8       8    Rachel Lee  29.0     USA   Female  62000.0      3.0
9       9   Carlos Ruiz   NaN  Mexico     Male  45000.0      8.0
10     10   Emily Davis  31.0     USA      NaN  58000.0      4.0

In [16]:
df2 = df.copy()
new_col_order = [col for col in df.columns if col != "id"] + ["id"]
df[new_col_order]

            name   age country   gender   income  id
0       John Doe  29.0     USA     Male  55000.0   1
1       John Doe  29.0     USA     Male  55000.0   1
2     Jane Smith   NaN  Canada   Female  62000.0   2
3           Alex   NaN     USA  Unknown  47000.0   3
4   Maria Garcia  34.0   Spain   Female      NaN   4
5         Li Wei  27.0   China     Male  51000.0   5
6            NaN  45.0   India   Female  73000.0   6
7     Ahmed Khan  38.0     NaN     Male  68000.0   7
8     Rachel Lee  29.0     USA   Female  62000.0   8
9    Carlos Ruiz   NaN  Mexico     Male  45000.0   9
10   Emily Davis  31.0     USA      NaN  58000.0  10

In [17]:
df2 = df.copy()

df2 = df2.drop_duplicates()
df2 = df2.fillna(0)
df2 = df2.sort_values("income")
df2 = df2.reset_index(drop=True)
df2.to_csv("sorted_data.csv")

In [18]:
df2 = df.copy()
df2.groupby("country")["income"].mean()
df2.groupby("gender")["income"].mean()

df2.groupby("country")["gender"].count()
df2.groupby("gender")["income"].max()

df2.groupby("country")["income"].agg(["mean","max","min"])
df2.groupby("country")["income"].aggregate(["mean","max","min"])

df2.groupby("country")["income"].agg(avg_salary="mean",max_salary = "max")

df2.groupby("country").agg({
    "age": "mean",
    "income": "mean"
})
df2.groupby("country").agg(
    avg_age=("age", "mean"),
    avg_salary=("income", "mean")
)   # rename aggregates on multiple cols

         avg_age  avg_salary
country
Canada       NaN     62000.0
China       27.0     51000.0
India       45.0     73000.0
Mexico       NaN     45000.0
Spain       34.0         NaN
USA         29.5     55400.0